name: Build EditorAI Android64 (patch-2)

on:
  push:
    branches:
      - patch-2
  workflow_dispatch:

jobs:
  build:
    name: Android64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: 'latest'
          combine: true
          target: Android64

  package:
    name: Package build
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: EditorAI-Android64
          path: ${{ steps.build.outputs.build-output }}
